config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :projects do
    resources :discussions, only: [:create, :index, :show, :new]
    resources :attachments, only: [:create, :destroy]
    member do
      get :remove_admin
      get :set_admin
    end
  end
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :project
  has_one_attached :file
end

app/models/discussion.rb
class Discussion < ApplicationRecord
    belongs_to :project
    belongs_to :user
    has_many :messages, dependent: :destroy
end
  

app/models/project.rb
class Project < ApplicationRecord
        belongs_to :user
        has_and_belongs_to_many :members, class_name: 'User', join_table: 'projects_users'
        has_many :attachments, dependent: :destroy
        has_many :discussions, dependent: :destroy
        has_many :messages
        
        def set_admin(user)
          user.update(admin: true)
        end
      
        def remove_admin(user)
          user.update(admin: false)
        end
      end
      

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_and_belongs_to_many :projects_as_member, class_name: 'Project', join_table: 'projects_users'

  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_project
  before_action :authenticate_user!

  def create
    @attachment = @project.attachments.new(attachment_params)
    if @attachment.save
      redirect_to @project, notice: 'Attachment was successfully created.'
    else
      redirect_to @project, alert: 'Error creating attachment.'
    end
  end

  def destroy
    @attachment = @project.attachments.find(params[:id])
    @attachment.destroy
    redirect_to @project, notice: 'Attachment successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def attachment_params
    params.require(:attachment).permit(:file)
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_action :set_project
  before_action :set_discussion, only: [:show, :destroy]

  def index
    @discussions = @project.discussions
  end
  
  def create
    @discussion = @project.discussions.build(discussion_params)
    @discussion.user = current_user

    if @discussion.save
      redirect_to project_path(@project), notice: 'Discussion was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Discussion was successfully deleted.' }
      format.js   # Optional: Handle JS response if using AJAX
    end
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_discussion
    @discussion = @project.discussions.find(params[:id])
  end

  def discussion_params
    params.require(:discussion).permit(:title, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy set_admin remove_admin]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @projects = Project.all

    if user_signed_in?
      @created_by_me = current_user.projects
    else
      @created_by_me = []
    end
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def set_admin
    user = User.find(params[:user_id])
    user.update(admin: true)
    @message = "Admin privileges granted."
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: @message }
      format.json { render :show, status: :ok, location: @project }
    end
  end

  def remove_admin
    user = User.find(params[:user_id])
    user.update(admin: false)
    @message = "Admin privileges revoked."
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: @message }
      format.json { render :show, status: :ok, location: @project }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :add_member, :user_id, :admin)
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
    redirect_to projects_path, notice: "Sorry! Not Authorized to Edit/Delete this Project because it was not created by you!" if @project.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :destroy]
    before_action :require_admin, only: [:destroy]
  
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to projects_path, notice: 'Successfully signed up!'
      else
        render :new
      end
    end
  
    def show
    end
  
    def destroy
      @user.destroy
      redirect_to root_path, notice: 'User was successfully deleted.'
    end
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
    def require_admin
      unless current_user.admin?
        redirect_to root_path, alert: 'You are not authorized to perform this action.'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/discussions/_discussion.html.erb
<li id="discussion-<%= discussion.id %>" class="list-group-item d-flex justify-content-between align-items-center">
  <div>
    <strong><%= discussion.user.email %>:</strong> <%= discussion.content %>
  </div>
  <div>
    <%= link_to 'Delete', project_discussion_path(discussion.project, discussion), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
  </div>
</li>

app/views/discussions/_form.html.erb
<%= form_with(model: [@project, @discussion], local: true) do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
  
    <%= form.label :content %>
    <%= form.text_area :content %>
  
    <%= form.submit %>
<% end %>
  

app/views/discussions/create.js.erb
// Append the new discussion to the list of discussions
<%= turbo_stream.append "discussion_section", partial: "discussions/discussion", locals: { discussion: @discussion } %>

// Clear the form and hide it
$("#discussion-form")[0].reset();
$("#discussion-form").hide();

app/views/discussions/destroy.js.erb
$("#discussion-<%= @discussion.id %>").remove();

app/views/discussions/index.html.erb
<h2>Discussions for <%= @project.name %></h2>

<ul class="list-group">
  <% @discussions.each do |discussion| %>
    <li class="list-group-item">
      <strong><%= discussion.user.email %>:</strong> <%= discussion.content %>
    </li>
  <% end %>
</ul>

app/views/discussions/show.html.erb
<h2>Discussion by <%= @discussion.user.email %></h2>

<p><%= @discussion.content %></p>

<%= link_to 'Back to Project', @project, class: 'btn btn-primary' %>

app/views/home/_header.html.erb
<ul class="nav">
  <li class="nav-item mr-auto">
    <%= link_to image_tag("logo.png", class: "nav-brand",height: 40, width: 40), "#" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{content_tag(:i, '', class: 'fa fa-plus')} Add Project".html_safe, new_project_path, class: "nav-link text-info" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{content_tag(:i, '', class: 'fa fa-cog')} Edit Profile".html_safe, edit_user_registration_path, class: "nav-link text-info" %>
  </li>
  <li class="nav-item">
  <%= link_to "#{content_tag(:i, '', class: 'fa fa-door-open')} Log Out".html_safe, destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-info" %>
</li>


</ul>

app/views/home/index.html.erb
<div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
  <div class="text-center">
    <%= image_tag 'logo.png', alt: 'Your Image', class: 'img-fluid mb-4', style: 'max-width: 300px; max-height: 200px;' %>
    <h1 class="display-1 font-weight-bold">COLLABORATE</h1>
    <h2 class="h3 mt-3">A project management tool for developers</h2>
    <div class="mt-4 d-flex justify-content-center">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info mr-2" %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBaseCamp Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

  </head>

  <body>
  <% if user_signed_in? %>
    <%= render 'home/header' %>
  <% end %>
  <br/>
  <% if notice %>
  <%= render 'layouts/alerts' %>
  <% end %>
  <br/>
    <%= yield %>
     <!-- Bootstrap
      JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "container mt-5") do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <% if @project.persisted? %>
        <div class="form-group">
          <%= form.label :add_member, "Add Member (email)" %>
          <div class="input-group">
            <%= form.text_field :add_member, class: "form-control" %>
            <div class="input-group-append">
              <div class="custom-control custom-switch mt-2 ml-4">
                <%= form.check_box :admin, class: "custom-control-input", id: "customSwitch1" %>
                <%= form.label :admin, "Admin", class: "custom-control-label", for: "customSwitch1"  %>
              </div>
              <% if @project.user.admin? %>
                  <%= link_to "Remove Admin", remove_admin_project_path(@project, user_id: @project.user_id), class: "btn btn-warning ml-3" %>
                   <% else %>
                      <%= link_to "Set Admin", set_admin_project_path(@project, user_id: @project.user_id), class: "btn btn-success ml-3" %>
                   <% end %>
              <button type="button" class="btn btn-warning ml-4">
                <i class="fa fa-user-plus" style="pointer-events: none; border-radius: 10%;"></i>
              </button>
            </div>
          </div>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>

      <div class="form-group mt-5 text-center">
        <%= form.submit class: "btn btn-dark" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class="card mb-3">
  <div class="card-body">
    <div class="project-box">
      <div class="card-header bg-dark text-white">
        <div class="d-flex align-items-center">
          <h5 class="card-title"><%= project.name %></h5>
          <%= link_to edit_project_path(project), class: "text-white ml-auto" do %>
            <%= content_tag(:i, '', class: 'fas fa-cog settings-icon') %>
          <% end %>
        </div>
        <div class="d-flex align-items-center">
        <a href="#" class="pencil-icon text-white"><i class="fas fa-pencil-alt mr-2"></i></a>
           <p class="card-text mr-2"><%= project.user.email %></p>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text"><%= project.description %></p>
      </div>
      <div class="card-footer bg-grey">
        <div class="d-flex align-items-center">
          <a href="#" class="users-icon" style="color: #000;"><i class="fas fa-users"></i></a>
          <a href="#" class="chat-icon mx-2" style="color: #000;"><i class="fas fa-comments"></i></a>
          <div class="ml-auto">
            <%= button_to content_tag(:i, '', class: 'fas fa-trash'), project, method: :delete, class: "btn btn-unstyled text-white bg-danger p-1 rounded" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="d-flex justify-content-end mb-3 mr-5 mt-4">
  <%= link_to "#{content_tag(:i, '', class: 'fa fa-eye')} Project Overview".html_safe, @project, class: "btn btn-info" %>
</div>

<div class="d-flex justify-content-end mb-2 mr-5">
  <%= button_to "#{content_tag(:i, '', class: 'fa fa-trash')} Delete Project".html_safe, @project, method: :delete, class: "btn btn-unstyled" %>
</div>

<h1 class="form-group text-center">Edit Project</h1>
<div class="d-flex justify-content-center align-items-center mb-3">
  <%= link_to @project, class: "text-dark mr-2" do %>
    <%= content_tag(:i, '', class: 'fas fa-pencil-alt') %>
  <% end %>
  <p class="card-text"><%= @project.user.email %></p>
</div>


<%= render "form", project: @project %>

<div class="d-flex mb-3 mt-4">
  <%= link_to "Back to projects", projects_path, class: "btn btn-secondary" %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>
<div class="container text-center">
 
<h1>Projects</h1>

  <div class="row">
    <div class="col-md-4 text-center">
      <div class="alert alert-secondary">
        <h6 class="alert-heading"><i class="fas fa-asterisk"></i> All Projects</h2>
      </div>
      <% @projects.each do |project| %>
        <%= render partial: 'projects/project', locals: { project: project } %>
      <% end %>
    </div>

    <div class="col-md-4 text-center">
      <div class="alert alert-secondary">
        <h6 class="alert-heading"><i class="fas fa-pen"></i> Created by Me</h2>
      </div>
      <% if @created_by_me.present? %>
        <% @created_by_me.each do |project| %>
          <%= render partial: 'projects/project', locals: { project: project } %>
        <% end %>
      <% else %>
        <p>No projects found.</p>
      <% end %>
    </div>

    <div class="col-md-4 text-center">
      <div class="alert alert-secondary">
        <h6 class="alert-heading"><i class="fas fa-users"></i> Shared with Me</h2>
      </div>
      <% if @shared_with_me.present? %>
        <% @shared_with_me.each do |project| %>
          <%= render partial: 'projects/project', locals: { project: project } %>
        <% end %>
      <% else %>
        <p>No projects found.</p>
      <% end %>
    </div>
  </div>

</div>

<% else %>
<div class="container-fluid vh-100 d-flex justify-content-center align-items-center">
  <div class="text-center">
    <%= image_tag 'logo.png', alt: 'Your Image', class: 'img-fluid mb-4', style: 'max-width: 300px; max-height: 200px;' %>
    <h1 class="display-1 font-weight-bold">COLLABORATE</h1>
    <h2 class="h3 mt-3">A project management tool for developers</h2>
    <div class="mt-4 d-flex justify-content-center">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info mr-2" %>
      <%= link_to "Login", new_user_session_path, class: "btn btn-info" %>
    </div>
  </div>
</div>


<% end %>

app/views/projects/new.html.erb
<h1  class="form-group text-center mt-5">New Project</h1>

<%= render "form", project: @project %>

<br>

app/views/projects/show.html.erb
<%= stylesheet_link_tag("projects") %>

<p class="card-text">
  <%= @project.user.email %> (
  <%= raw(@project.user.admin? ? '<i class="fas fa-crown"></i> Admin' : '<i class="fas fa-user"></i> User') %>
  )
</p>

  <h1 class="form-group text-center">Project!!</h1>

  <div class="d-flex justify-content-center align-items-center mb-3">
    <%= link_to edit_project_path(@project), class: "text-dark mr-2" do %>
      <%= content_tag(:i, '', class: 'fas fa-pencil-alt') %>
    <% end %>
    <p class="card-text">Created by: <%= @project.user.email %></p>
  </div>

<div class = "projects_design_page">
  <div class="projects_page_left_hand">
    <div class="mr-4">
      <h5>Members:</h5>
      <div class="d-flex mb-3">
        <%= link_to edit_project_path(@project), class: "text-dark mr-2" do %>
          <%= content_tag(:i, '', class: 'fas fa-pencil-alt') %>
        <% end %>
        <p class="card-text"><%= @project.user.email %></p>
      </div>
      <%= render @project %>
    </div>

    <!-- Discussion Section -->
    <%= turbo_frame_tag "discussion_section" do %>
    <h2 class="mb-4 discussion_header">Discussions</h2>
    <div id="discussion-section">
      <button id="new-discussion-btn" class="btn btn-primary mb-3">New Discussion</button>
      
      <%= form_with(model: [ @project, Discussion.new ], local: false, id: "discussion-form", class: "mb-4", remote: true) do |form| %>
        <div class="form-group">
          <%= form.label :content, "Your Message" %>
          <%= form.text_area :content, class: "form-control", rows: 3 %>
        </div>
        <%= form.submit 'Send', class: "btn btn-success" %>
      <% end %>

      <ul class="list-group">
        <% @project.discussions.each do |discussion| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
              <strong><%= discussion.user.email %>:</strong> <%= discussion.content %>
            </div>
            <div>
              <%= link_to 'Delete', project_discussion_path(@project, discussion), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <h2 class="mb-4 discussion_header">Attachments</h2>
    <%= form_with(model: [ @project, Attachment.new ], local: true, class: "mb-4") do |form| %>
      <div class="form-group">

        <%= form.file_field :file, class: "form-control-file" %>
      </div>
      <%= form.submit 'Upload File', class: "btn btn-primary" %>
    <% end %>

    <ul class="list-group mb-5">
      <% @project.attachments.each do |attachment| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= link_to attachment.file.filename, url_for(attachment.file), class: "mr-3" %>
          <%= link_to 'Delete', project_attachment_path(@project, attachment), data: { turbo_method: :delete }, class: "btn btn-sm btn-danger" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="projects_page_right_hand">
      <%= link_to "#{content_tag(:i, '', class: 'fas fa-cog settings-icon')} Edit Project".html_safe, edit_project_path(@project), class: "btn btn-info" %>
      <%= link_to "#{content_tag(:i, '', class: 'fas fa-users')} Members".html_safe, edit_project_path(@project), class: "btn btn-secondary mb-2" %>
      <%= link_to "#{content_tag(:i, '', class: 'fas fa-tags')} Topics".html_safe, edit_project_path(@project), class: "btn btn-secondary mb-2" %>
      <%= link_to "#{content_tag(:i, '', class: 'fas fa-tasks')} Tasks".html_safe, edit_project_path(@project), class: "btn btn-secondary mb-2" %>
      <%= link_to "#{content_tag(:i, '', class: 'fas fa-paperclip')} Attachments".html_safe, edit_project_path(@project), class: "btn btn-secondary mb-2" %>
    </div>
</div>



<script>
document.getElementById('new-discussion-btn').addEventListener('click', function() {
    var form = document.getElementById('discussion-form');
    if (form.style.display === 'none') {
      form.style.display = 'block';
    } else {
      form.style.display = 'none';
    }
  });
</script>